(function(){var _svc=null;var _sessionSvc=null;var _pingSvc=null;const eResponseCodes=Object.freeze({ERROR:0,SUCCESS:1});(function(){function services(){var _registeredServices={};var _ref=this;function initialize(){}function registerService(name,handler){if(name&&handler){name=name.toUpperCase();if(!_registeredServices[name])_registeredServices[name]=handler}}function unregisterService(name){if(name){name=name.toUpperCase();if(_registeredServices[name])delete _registeredServices[name]}}
function execute(name,data){return new Promise((resolve,reject)=>{if(name){name=name.toUpperCase();if(_registeredServices[name])_registeredServices[name].apply(null,data).then(result=>{resolve(result)}).catch(err=>{reject(err)});else reject(`Method not found ${name}`)}else reject(`Name is null or undefined ${name}`)})}Object.defineProperty(_ref,"registerService",{enumerable:true,configurable:false,writable:false,value:registerService});Object.defineProperty(_ref,"unregisterService",{enumerable:true,
configurable:false,writable:false,value:unregisterService});Object.defineProperty(_ref,"execute",{enumerable:true,configurable:false,writable:false,value:execute});return _ref}_svc=new services})();(function(){function PingService(){var _ref=this;var _states={"READY":0,"SETUP":1,"SENT":2,"PROCESS":3,"COMPLETED":4};var _interval={id:null,time:3E4,isRunning:false};var _serverUrl=location.origin+"/";function initialize(){if(_svc)_svc.registerService("ping",ping)}function ping(){return new Promise((resolve,
reject)=>{let xhr=new XMLHttpRequest;xhr.withCredentials=false;xhr.onreadystatechange=function(e){var evt=e.target;if(evt.readyState===_states.COMPLETED)if(evt.status===200)resolve({code:eResponseCodes.SUCCESS,data:evt});else reject({code:eResponseCodes.ERROR,data:evt})};_sessionSvc.getAll().then(list=>{xhr.open("GET",`${_serverUrl}?cmd?cmd=ping&id=${JSON.stringify(list)}`,true);xhr.send()})})}function start(){if(!_interval.isRunning){clearInterval(_interval.id);_interval.id=setInterval(()=>{ping()},
_interval.time);_interval.isRunning=true}}function stop(){clearInterval(_interval.id);_interval.isRunning=false}initialize();Object.defineProperty(_ref,"start",{enumerable:true,configurable:false,writable:false,value:start});Object.defineProperty(_ref,"stop",{enumerable:true,configurable:false,writable:false,value:stop});return _ref}_pingSvc=new PingService})();(function(){function SessionService(){var _ref=this;var _sessions={};var _exportExcept=["sessionId","lastContactTime"];var _purgeInterval=
{id:null,time:5E3,isRunning:false,expiredTime:35E3};function initialize(){if(_svc){_svc.registerService("SESSION-ADD",add);_svc.registerService("SESSION-UPDATE",update);_svc.registerService("SESSION-REMOVE",remove);start()}}function start(){if(!_purgeInterval.isRunning){clearInterval(_purgeInterval.id);_purgeInterval.id=setInterval(()=>{purge()},_purgeInterval.time);_purgeInterval.isRunning=true}}function stop(){clearInterval(_purgeInterval.id);_purgeInterval.isRunning=false}function purge(){let d=
Date.now();for(let sessionId in _sessions)if(d-_sessions[sessionId].lastContactTime>_purgeInterval.expiredTime)delete _sessions[sessionId]}function add(data){return new Promise((resolve,reject)=>{if(data){let idKey=data?.gwsid?.toUpperCase();if(!_sessions[idKey]){_sessions[idKey]={...data,sessionId:data.gwsid,lastContactTime:Date.now()};_pingSvc.start();resolve({code:eResponseCodes.SUCCESS})}else reject(resolve({code:eResponseCodes.ERROR,data:`SessionId is already defined "${data?.gwsid||""}"`}))}else reject(resolve({code:eResponseCodes.ERROR,
data:`SessionId is undefined or null`}))})}function update(data){return new Promise((resolve,reject)=>{if(data){let idKey=data?.gwsid?.toUpperCase();if(_sessions[idKey]){let pData=_sessions[idKey];_sessions[idKey]={...pData,...data,...{sessionId:data.gwsid,lastContactTime:Date.now()}};_pingSvc.start();resolve({code:eResponseCodes.SUCCESS})}else add(data).then(r=>resolve(r)).catch(err=>reject(err))}else reject(resolve({code:eResponseCodes.ERROR,data:`SessionId is undefined or null`}))})}function remove(data){return new Promise((resolve,
reject)=>{if(data){let idKey=data?.gwsid?.toUpperCase();if(_sessions[idKey]){delete _sessions[idKey];resolve({code:eResponseCodes.SUCCESS})}else reject(resolve({code:eResponseCodes.ERROR,data:`SessionId is not defined "${data?.gwsid||""}"`}))}else reject(resolve({code:eResponseCodes.ERROR,data:`SessionId is undefined or null`}))})}function getAll(){return new Promise((resolve,reject)=>{try{let response=[];Object.keys(_sessions).forEach(id=>{let c={..._sessions[id]};_exportExcept.forEach(field=>{delete c[field]});
response.push(c)});resolve(response)}catch(err){reject(err)}})}initialize();Object.defineProperty(_ref,"getAll",{enumerable:true,configurable:false,writable:false,value:getAll});return _ref}_sessionSvc=new SessionService})();onconnect=function(event){const port=event.ports[0];port.onmessage=function(e){let d=e.data?.data||[];d=!(d instanceof Array)?[d]:d;if(e.data?.name)_svc.execute(e.data.name,d).then(r=>{port.postMessage(r)}).catch(e=>{port.postMessage(e)})}}})();
