thinVncConsts = {
    "fullColor": "Full Color",
    "colors256": "256 Color",
    "ctrlAltDel": "Ctrl+Alt+Del",
    "ctrlEsc": "Ctrl+Esc",
    "remoteKbdLayout": "Remote Keyboard Layout",
    "help": "Help",
    "enableMouseKbdControl": "Enables mouse and keyboard control.",
    "productDescription": "<%=$LICPROD%>",
    "closeSession": "close <%=$LICPROD%> session on exit",
    "control": "Control",
    "pause": "Pause",
    "resume": "Resume",
    "requestFullDisplayUpd": "Request a full display update.",
    "scaleDisplayToFitWin": "Scale the display to fit in the current window.",
    "refresh": "Refresh",
    "scale": "Scale",
    "changeColorDepth": "Changes color depth.",
    "colors": "Colors",
    "nextMonitor": "Next Monitor.",
    "monitor": "Monitor",
    "showClipboardWindow": "Shows the clipboard window.",
    "clipboard": "Clipboard",
    "kbdShortcuts": "Keyboard shortcuts.",
    "keyboard": "Keyboard",
    "disconnectThinVNCSess": "Disconnect your Screen Sharing session.",
    "disconnect": "Disconnect",
    "disconnectConfirm": "A session is active. Are you sure you want to disconnect?",
    "scrollToolbarToRight": "Scroll toolbar to the right or show toolbar handle",
    "scrollToolbarToLeft": "Scroll toolbar to the left",
    "copyRemoteClipbHere": "Copy the remote clipboard here",
    "pasteTextRemoteComput": "Paste the text below in the remote computer",
    "paste": "Paste",
    "clearTextBelow": "Clear the text below",
    "ctrlAltEnd": "CTRL+ALT+END",
    "openNTSecurityDlg": " (Open the Microsoft Windows NT Security dialog box)",
    "altPageUp": "ALT+PAGE UP",
    "switchBetweenProgsLR": " (Switch between programs from left to right)",
    "altPageDown": "ALT+PAGE DOWN",
    "switchBetweenProgsRL": " (Switch between programs from right to left)",
    "altInsert": "ALT+INSERT",
    "cycleThroughProgs": " (Cycle through the programs in most recently used order)",
    "altHome": "ALT+HOME",
    "displyStartMenu": " (Display the Start menu)",
    "altDelete": "ALT+DELETE",
    "displayWinMenu": " (Display the Windows menu)",
    "ctrlAltMinus": "CTRL+ALT+Minus sign (-)",
    "placeSnapshotEntire": " (Place a snapshot of the entire client window area on the Thinfinity Remote Desktop server clipboard and provide the same functionality as pressing PRINT SCREEN on a local computer.)",
    "ctrlAltPlus": "CTRL+ALT+Plus sign (+)",
    "placeSnapshotActiveWin": " (Place a snapshot of the active window in the client on the Thinfinity Remote Desktop server clipboard and provide the same functionality as pressing ALT+PRINT SCREEN on a local computer.)",
    "thinVNCScreenSharing": "Thinfinity Screen Sharing",
    "thinVNCRemoteDesktop": "Thinfinity Remote Desktop",
    "connCouldNotBeEstabl": "The connection could not be established",
    "startingProgram": "Starting program...",
    "connectionClosed": "Connection closed",
    "thankYouAttendMetting": "Thank you for attending the meeting! ",
    "restart": "Restart",
    "invalidTicket": "Invalid ticket",
    "editPC": "Edit PC",
    "pleaseWait": "Please wait...",
    "waitingForAuthorization": "Waiting for authorization",
    "settings": "Settings",
    "settingsTooltip": "Open connection settings",
    "setAsDefault": "Set as default mode",
    "printScreen": "Print Screen",
    "actions": "Actions",
    "options": "Options"
};